### ISSUE TITLE
having 2 locations, one for *complete* one for *incomplete* proposals

### ISSUE THREAD

**Issue by ufobat** [perl-gsoc-2019/ideas#3]
For examlpe me TLS proposal is more or less a rough idea, I am not able to mentor it.

I would be unhappy if we had to delete it because it is (maybe still) a valid idea. Maybe someone could pick up an incomplete proposal and mentor it.

**Comment by AlexDaniel** [comment]
I agree. Please. Also having to do stuff in a repo is a PITA, a wiki is a more suitable place.

**Comment by JJ** [comment]
El lun., 28 ene. 2019 a las 10:03, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> I agree. Please. Also having to do stuff in a repo is a PITA, a wiki is a
> more suitable place.
>

You can comment, as you are doing now, in a repo. You can assign issues,
and close them from commits. You can't do all that with a wiki. Only
advantage in a wiki is that anyone can edit it, but you can also do that
here via a pull request.

I can flesh out the ideas and assign a suitable mentor, no problem at all
with that.

**Comment by JJ** [comment]
Except when you have to flesh them out to actually publish them, as is needed for the proposal.
I'll open an issue for that kind of things, anyway. Better than a wiki for discussion, or requests for clarification.

**Comment by AlexDaniel** [comment]
Then maybe proposal should be filed as an issue originally, and then committed when they're fully ready.

**Comment by JJ** [comment]
That's another idea. I'll add it to #8
